
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RDECLARE = 28;
  public static final int MENQUE = 14;
  public static final int RSTRING = 30;
  public static final int RTRUE = 12;
  public static final int RWHILE = 37;
  public static final int POR = 9;
  public static final int CONCAT = 11;
  public static final int ENTERO = 23;
  public static final int RFALSE = 13;
  public static final int LLAVIZQ = 5;
  public static final int RELSE = 36;
  public static final int IDENTIFICADOR = 33;
  public static final int RPRINT = 27;
  public static final int IGUALQUE = 19;
  public static final int IGUAL = 32;
  public static final int DIVIDIDO = 10;
  public static final int MAYIGUALQUE = 17;
  public static final int UMENOS = 26;
  public static final int RDO = 38;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 24;
  public static final int MENIGUALQUE = 16;
  public static final int RELSEIF = 35;
  public static final int error = 1;
  public static final int CADENA = 25;
  public static final int MENOS = 8;
  public static final int MAYQUE = 15;
  public static final int LLAVDER = 6;
  public static final int RNUMBER = 29;
  public static final int PTCOMA = 2;
  public static final int ROR = 21;
  public static final int RBOOLEAN = 31;
  public static final int RFOR = 39;
  public static final int PARDER = 4;
  public static final int RIF = 34;
  public static final int RNOT = 20;
  public static final int RAND = 22;
  public static final int DIFQUE = 18;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "CONCAT",
  "RTRUE",
  "RFALSE",
  "MENQUE",
  "MAYQUE",
  "MENIGUALQUE",
  "MAYIGUALQUE",
  "DIFQUE",
  "IGUALQUE",
  "RNOT",
  "ROR",
  "RAND",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "RPRINT",
  "RDECLARE",
  "RNUMBER",
  "RSTRING",
  "RBOOLEAN",
  "IGUAL",
  "IDENTIFICADOR",
  "RIF",
  "RELSEIF",
  "RELSE",
  "RWHILE",
  "RDO",
  "RFOR"
  };
}

